database:
  database_path: "database/data.json"

front_end:
  template_path: "front_end/*"

user:
  user_bank_path: "database/users.json"
  user_hash_path: "database/users_hash.json"
  question_progress_path: "database/question_progress.json"

auth:
 jwt_secret: "your_jwt_secret_key"
 expiration_time: 604800
